// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Position.Module.DAL;

#nullable disable

namespace backend.Position.Module.DAL.Migrations
{
    [DbContext(typeof(TypePosadDbContext))]
    partial class TypePosadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Position.Module.DAL.Models.TypePosad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Active_AD")
                        .HasColumnType("bit");

                    b.Property<bool>("Active_BOS")
                        .HasColumnType("bit");

                    b.Property<short>("Category")
                        .HasColumnType("smallint");

                    b.Property<bool>("CheckDnVidp")
                        .HasColumnType("bit");

                    b.Property<bool>("LogLinPers")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("NameFull")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameTbl1C8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("PercentForTabel")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<bool>("TrUtrPodatk")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TypePosads");
                });
#pragma warning restore 612, 618
        }
    }
}
